[EN] Just update
New file of snipet and installation script of Guix.

diff --git a/snippets/sh-mode/sh_main b/snippets/sh-mode/sh_main
--- a/snippets/sh-mode/sh_main
+++ b/snippets/sh-mode/sh_main
@@ -2,12 +2,14 @@
 # name: sh_main
 # key: shm_
 # --
-# File           : `(buffer-name)`
-# Created        : `(format-time-string "<%Y-%m-%d %a %T %Z>" (current-time))`
-# Last Modified  : `(format-time-string "<%Y-%m-%d %a %T %Z>" (current-time))`
-# Author         : `(user-login-name)`
-# Maintainer(s)  :
-# Short          :
+#!/usr/bin/env bash
+# File     : `(buffer-name)`
+# Created  : `(format-time-string "<%Y-%m-%d %a %T %Z>" (current-time))`
+# Modified : `(format-time-string "<%Y-%m-%d %a %T %Z>" (current-time))`
+# Author   : `(user-login-name)`
+# Synopsis :
+
+set -e
 
 # Commentary:
 #
@@ -18,20 +20,62 @@
 #       + Script initiation.
 #
 # ==============================================================================
+# ------------------------------------------------------------------------------
+#+DEFAUL_CONFIG
 
-VERSION=0.0.1
-CMDNAME=`(buffer-name)`
-TIMESTAMP="$(date "+%Y%m%d%H%M%S")"
-ABS_PATH="$(dirname "$(readlink -f "$0")")"
-REQUIRE=(nc dig nmap)
+
+CMD_VER=0.0.1
+CMDNAME=wds-guix-install.sh
+REQUIRE=(dirname readlink)
+
+OK=\$'[  \033[32;1mOK\033[0m  ]'
+FAIL=\$'[ \033[31;1mFAIL\033[0m ]'
+
+_err()
+{ # All errors go to stder.
+    printf "[%s]: %s\n" "\$(date +%s.%3N)" "\$1"
+}
+
+_msg()
+{ # Default message fro stdout.
+    printf "[%s]: %s\n" "\$(date +%s.%3N)" "$1"
+}
+
+chk_require()
+{ # Check that every required command is available.
+    declare -a cmds
+    declare -a warn
+
+    cmds=(\$\{1\})
+
+    _msg "--- [\$FUNCNAME] ---"
+    [ "\${#cmds}" -eq "0" ] &&
+        { _err "No arguments provided."; return 1; }
+
+    for c in \${cmds[@]}; do
+        command -v "\$c" 2>&1 >/dev/null
+        [ "\$?" -eq "1" ] &&
+            warn+=("\$c")
+    done
+
+    [ "\${#warn}" -ne 0 ] &&
+        { _err "\${FAIL} Commands \${warn[*]} are not avialable, install them first.";
+          return 1; }
+
+    _msg "\${OK} verification of required commands completed"
+}
 
 # ------------------------------------------------------------------------------
 #+MAIN
 
-main() {
+main()
+{
+    printf "Start %s %sv at %s\n\n" "\$CMDNAME" "\$CMD_VER" "\$(date)"
+    chk_require "\${REQUIRE[*]}"
 
+    ABS_PATH="\$(dirname "\$(readlink -f "\$0")")"
+    echo "\$ABS_PATH"
 }
 
-main "$@"
+main "\$@"
 # End of `(buffer-name)`
-
